from dynamixel_sdk import *

ADDR_MX_TORQUE_ENABLE = 64
ADDR_MX_GOAL_POSITION = 116
ADDR_MX_PRESENT_POSITION = 132

PROTOCOL_VERISION = 1.0

DXL_ID = 1
DAUDRATE = 57600
DEVICENAME= '/dev/ttyS0'
TORQUE_ENABLE = 1
TORQUE_DISABLE = 0
DXL_MINIMUM_POSITION_VALUE = 
